# Generated by Django 6.0.5 on 2026-05-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dimension',
            field=models.CharField(choices=[('Decision Making', 'Decision Making'), ('Team Communication', 'Team Communication'), ('Strategic Thinking', 'Strategic Thinking')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
